# Generated by Django 3.0.8 on 2021-03-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='practica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.Practica'),
        ),
    ]
