# Generated by Django 3.0.8 on 2021-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_practica'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='clavediahoraservicio',
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('servicio', 'fecha', 'hora'), name='clavediahoraservicio'),
        ),
    ]
