# Generated by Django 3.0.8 on 2021-03-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20210309_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos.Paciente'),
        ),
    ]
