# Generated by Django 3.0.8 on 2021-03-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_novedades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novedades',
            new_name='Novedad',
        ),
    ]
