# Generated by Django 3.0.8 on 2021-03-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_auto_20210317_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
